

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int PRUcode[] =  {
     0x91042480,
     0x1d04e0e0,
     0x81042480,
     0x240100e0,
     0x240002c1,
     0x24402881,
     0xe1002180,
     0x240010c0,
     0x24000080,
     0x240002c1,
     0x24402c81,
     0xe1002180,
     0x810c3880,
     0x910c3884,
     0x6f01e4ff,
     0x91043880,
     0x91003883,
     0x1ee3fefe,
     0x91083881,
     0x11ffe1e1,
     0x0501e1e1,
     0x6f00e1ff,
     0x1ce3fefe,
     0x91083881,
     0x11ffe1e1,
     0x240100e2,
     0x0ce2e1e1,
     0x0501e1e1,
     0x6f00e1ff,
     0x0501e0e0,
     0x6f00e0f3,
     0x2400241f,
     0x2a000000 };

